name: kenczler
favicon: null
layout_spectrum: 0.2064895040821284
typography_spectrum: 0.8813955944497138
title: Original Works and Stuff I liked
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5803980797063559
  lightness: 0.5533976033329964
  saturation: 0.7904419894330204
  rhythmicContrast: 0.7095610129181296
purpose: []
